(() => {
  'use strict';
  const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
  const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  let token=localStorage.getItem('idrokAuthToken')||'',admin=null,users=[],stats=null;
  async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{}) ,...(options.headers||{})}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Server bilan aloqa xatosi.');return payload}
  function toast(message){const node=$('#adminToast');node.textContent=message;node.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove('show'),2200)}
  function cacheAdmin(user,newToken){admin=user;if(newToken){token=newToken;localStorage.setItem('idrokAuthToken',token)}localStorage.setItem('idrokCurrentUser',user.email);let list=[];try{list=JSON.parse(localStorage.getItem('idrokUsers')||'[]')}catch{}const index=list.findIndex(item=>item.email===user.email);if(index>=0)list[index]={...list[index],...user};else list.push(user);localStorage.setItem('idrokUsers',JSON.stringify(list));localStorage.setItem('idrokState',JSON.stringify({completed:user.completed||[],score:user.score||0,impulse:999999999,theme:user.theme||'light'}))}
  function number(value){return Number(value||0).toLocaleString('uz-UZ')}
  function initials(name){return String(name||'AD').split(/\s+/).slice(0,2).map(part=>part[0]).join('').toUpperCase()}
  function renderStats(){const s=stats.stats;$('#statUsers').textContent=number(s.users);$('#sideUserCount').textContent=s.users;$('#consoleUsers').textContent=number(s.users);$('#statNew').textContent=`+${s.newThisWeek} bu hafta`;$('#statLessons').textContent=number(s.totalLessons);$('#statImpulse').textContent=number(s.totalImpulse);$('#statFocus').textContent=`${number(s.focusMinutes)}m`;$('#statPlants').textContent=`${number(s.plantsGrown)} o‘simlik o‘sgan`;$('#statSessions').textContent=s.activeSessions;$('#statDisabled').textContent=s.disabled;$('#statAdmins').textContent=s.admins;$('#gradeBars').innerHTML=stats.grades.map(item=>`<div class="grade-row"><div><b>${escapeHTML(item.label)} fizika</b><small>${number(item.completed)} / ${number(item.total)} dars • ${Number(item.percent)||0}%</small></div><span><i style="width:${Math.max(0,Math.min(100,Number(item.percent)||0))}%"></i></span></div>`).join('');$('#recentUsers').innerHTML=stats.recent.length?stats.recent.map(user=>`<div class="recent-user"><span>${escapeHTML(initials(user.name))}</span><div><b>${escapeHTML(user.name)}</b><small>${escapeHTML(user.email)}</small></div><em>${user.courseProgress.grade7+user.courseProgress.grade8+user.courseProgress.grade9+user.courseProgress.grade10+user.courseProgress.grade11} dars</em><em>${new Date(user.createdAt).toLocaleDateString('uz-UZ')}</em></div>`).join(''):'<div class="empty-row">Hozircha haqiqiy foydalanuvchilar yo‘q.</div>'}
  function renderUsers(query=''){const clean=query.trim().toLowerCase(),filtered=users.filter(user=>(user.name+' '+user.email).toLowerCase().includes(clean));$('#usersBody').innerHTML=filtered.map(user=>{const progress=user.courseProgress,safeId=escapeHTML(user.id);return`<tr><td><div class="user-cell"><span>${escapeHTML(initials(user.name))}</span><div><b>${escapeHTML(user.name)}${user.role==='admin'?' • ADMIN':''}</b><small>${escapeHTML(user.email)}</small></div></div></td><td><div class="mini-progress"><i>7: ${progress.grade7}</i><i>8: ${progress.grade8}</i><i>9: ${progress.grade9}</i><i>10: ${progress.grade10}</i><i>11: ${progress.grade11}</i></div></td><td>${user.role==='admin'?'∞':number(user.impulse)} ϟ</td><td>${Number(user.garden.plants)||0} nihol • ${Number(user.garden.focusMinutes)||0}m</td><td><span class="status-pill ${user.disabled?'disabled':''}">${user.disabled?'BLOKLANGAN':'FAOL'}</span></td><td><div class="user-actions">${user.role==='admin'?'<span>—</span>':`<button data-user-action="grant-impulse" data-user-id="${safeId}">+500 ϟ</button><button data-user-action="toggle-disabled" data-user-id="${safeId}">${user.disabled?'Ochish':'Bloklash'}</button><button data-user-action="revoke-sessions" data-user-id="${safeId}">Chiqish</button>`}</div></td></tr>`}).join('');$('#usersEmpty').style.display=filtered.length?'none':'block'}
  async function loadDashboard(){const [statsResult,usersResult]=await Promise.all([api('/api/admin/stats'),api('/api/admin/users')]);stats=statsResult;users=usersResult.users;renderStats();renderUsers();document.body.classList.remove('admin-loading')}
  async function start(){try{const setup=await api('/api/admin/bootstrap-status');if(setup.needsSetup){document.body.classList.remove('admin-loading');$('#adminSetup').classList.add('open');$('#adminSetup').setAttribute('aria-hidden','false');return}if(!token){location.replace('index.html?auth=login&next=admin.html');return}const me=await api('/api/me');if(me.user.role!=='admin'){localStorage.removeItem('idrokAuthToken');localStorage.removeItem('idrokCurrentUser');location.replace('index.html?auth=login&next=admin.html');return}cacheAdmin(me.user);$('#adminName').textContent=me.user.name;$('#adminAvatar').textContent=initials(me.user.name);await loadDashboard()}catch(error){document.body.classList.remove('admin-loading');toast(error.message)}}
  $('#adminSetupForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),button=form.querySelector('button'),message=form.querySelector('.setup-message');button.disabled=true;message.textContent='';try{const result=await api('/api/admin/bootstrap',{method:'POST',body:JSON.stringify({name:data.get('name').trim(),email:data.get('email').trim(),password:data.get('password')})});cacheAdmin(result.user,result.token);$('#adminSetup').classList.remove('open');$('#adminName').textContent=result.user.name;$('#adminAvatar').textContent=initials(result.user.name);await loadDashboard();toast('Admin markazi tayyor!')}catch(error){message.textContent=error.message}finally{button.disabled=false}});
  function switchView(view){$$('[data-admin-view]').forEach(button=>button.classList.toggle('active',button.dataset.adminView===view));$$('.admin-view').forEach(section=>section.classList.toggle('active',section.id===`view-${view}`));$('#viewTitle').textContent={overview:'Umumiy holat',users:'Foydalanuvchilar',courses:'Kurslar nazorati',system:'Tizim holati'}[view]||'Admin';$('.admin-side').classList.remove('open')}
  $$('[data-admin-view]').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.adminView)));
  $('#userSearch').addEventListener('input',event=>renderUsers(event.target.value));
  $('#usersBody').addEventListener('click',async event=>{const button=event.target.closest('[data-user-action]');if(!button)return;button.disabled=true;try{await api('/api/admin/user-action',{method:'POST',body:JSON.stringify({userId:button.dataset.userId,action:button.dataset.userAction,amount:500})});await loadDashboard();toast('Foydalanuvchi yangilandi.')}catch(error){toast(error.message)}finally{button.disabled=false}});
  $('#refreshAdmin').addEventListener('click',async()=>{await loadDashboard();toast('Ma’lumotlar yangilandi.')});
  $('#adminMenu').addEventListener('click',()=>$('.admin-side').classList.add('open'));
  $('#adminLogout').addEventListener('click',async()=>{try{await api('/api/logout',{method:'POST'})}catch{}localStorage.removeItem('idrokAuthToken');localStorage.removeItem('idrokCurrentUser');location.href='index.html?auth=login'});
  start();
})();
