(() => {
  'use strict';

  const simulations = Object.freeze({
    diffusion: {slug: 'diffusion', title: 'Diffuziya'},
    atomic: {slug: 'atomic-interactions', title: 'Atomlarning o‘zaro ta’siri'},
    molarity: {slug: 'molarity', title: 'Molyarlik'},
    concentration: {slug: 'concentration', title: 'Konsentratsiya'},
    gas: {slug: 'gas-properties', title: 'Gaz xossalari'},
    statesBasics: {slug: 'states-of-matter-basics', title: 'Moddaning agregat holatlari'},
    gasesIntro: {slug: 'gases-intro', title: 'Gazlar: kirish'},
    moleculeShapesBasics: {slug: 'molecule-shapes-basics', title: 'Molekula shakllari: asoslar'},
    energy: {slug: 'energy-forms-and-changes', title: 'Energiya shakllari va o‘zgarishlari'},
    friction: {slug: 'friction', title: 'Ishqalanish'},
    skate: {slug: 'energy-skate-park', title: 'Energiya skeyt-parki'},
    skateBasics: {slug: 'energy-skate-park-basics', title: 'Energiya skeyt-parki: asoslar'},
    greenhouse: {slug: 'greenhouse-effect', title: 'Issiqxona effekti'},
    polarity: {slug: 'molecule-polarity', title: 'Molekula qutbliligi'},
    pressure: {slug: 'under-pressure', title: 'Bosim ostida'},
    density: {slug: 'density', title: 'Zichlik'},
    moleculeShapes: {slug: 'molecule-shapes', title: 'Molekula shakllari'},
    springBasics: {slug: 'masses-and-springs-basics', title: 'Massalar va prujinalar: asoslar'},
    hookes: {slug: 'hookes-law', title: 'Guk qonuni'},
    states: {slug: 'states-of-matter', title: 'Moddaning holatlari'},
    light: {slug: 'bending-light', title: 'Yorug‘likning sinishi'},
    opticsBasics: {slug: 'geometric-optics-basics', title: 'Geometrik optika: asoslar'},
    optics: {slug: 'geometric-optics', title: 'Geometrik optika'},
    moleculesLight: {slug: 'molecules-and-light', title: 'Molekulalar va yorug‘lik'},
    spectrum: {slug: 'blackbody-spectrum', title: 'Absolyut qora jism spektri'},
    gravity: {slug: 'gravity-and-orbits', title: 'Gravitatsiya va orbitalar'},
    wavesIntro: {slug: 'waves-intro', title: 'To‘lqinlar: kirish'},
    circuits: {slug: 'circuit-construction-kit-dc-virtual-lab', title: 'Elektr zanjiri virtual laboratoriyasi'},
    staticElectricity: {slug: 'balloons-and-static-electricity', title: 'Sharlar va statik elektr'},
    chargesFields: {slug: 'charges-and-fields', title: 'Zaryadlar va maydonlar'},
    coulomb: {slug: 'coulombs-law', title: 'Kulon qonuni'},
    capacitor: {slug: 'capacitor-lab-basics', title: 'Kondensator laboratoriyasi'},
    faraday: {slug: 'faradays-electromagnetic-lab', title: 'Faradey elektromagnit laboratoriyasi', locale: 'en'},
    generator: {slug: 'generator', title: 'Generator', locale: 'en'},
    electromagnets: {slug: 'magnets-and-electromagnets', title: 'Magnitlar va elektromagnitlar', locale: 'en'},
    compass: {slug: 'magnet-and-compass', title: 'Magnit va kompas', locale: 'en'},
    interference: {slug: 'wave-interference', title: 'To‘lqinlar interferensiyasi'},
    sound: {slug: 'sound-waves', title: 'Tovush to‘lqinlari'},
    normalModes: {slug: 'normal-modes', title: 'Normal tebranishlar'},
    fourier: {slug: 'fourier-making-waves', title: 'Furye: to‘lqin yaratish'},
    collision: {slug: 'collision-lab', title: 'To‘qnashuv laboratoriyasi'},
    vectors: {slug: 'vector-addition', title: 'Vektorlarni qo‘shish'},
    projectile: {slug: 'projectile-motion', title: 'Gorizontal va qiya otilgan jism'},
    solarSystem: {slug: 'my-solar-system', title: 'Mening Quyosh sistemam'},
    nucleus: {slug: 'build-a-nucleus', title: 'Yadro yarating'},
    hydrogen: {slug: 'models-of-the-hydrogen-atom', title: 'Vodorod atomi modellari', locale: 'en'},
    photoelectric: {slug: 'build-an-atom', title: 'Atom tuzilishini yarating'},
    quantumInterference: {slug: 'isotopes-and-atomic-mass', title: 'Izotoplar va atom massasi'},
    quantumTunneling: {slug: 'wave-on-a-string', title: 'Arqondagi to‘lqin'},
    rutherford: {slug: 'rutherford-scattering', title: 'Rezerford sochilishi'},
    radioactiveDating: {slug: 'faradays-law', title: 'Faradey qonuni'},
    betaDecay: {slug: 'gravity-force-lab', title: 'Gravitatsiya kuchi laboratoriyasi'},
    alphaDecay: {slug: 'vector-addition-equations', title: 'Vektor tenglamalari'},
    springs: {slug: 'masses-and-springs', title: 'Massalar va prujinalar'},
    pendulum: {slug: 'pendulum-lab', title: 'Mayatnik laboratoriyasi'},
    projectileData: {slug: 'projectile-data-lab', title: 'Otilish ma’lumotlari laboratoriyasi', locale: 'en'},
    balance: {slug: 'balancing-act', title: 'Muvozanat'},
    forces: {slug: 'forces-and-motion-basics', title: 'Kuch va harakat asoslari'},
    ramp: {slug: 'curve-fitting', title: 'Grafikni egri chiziqqa moslash'},
    travoltage: {slug: 'john-travoltage', title: 'Statik zaryad tajribasi'},
    electricHockey: {slug: 'calculus-grapher', title: 'Harakat grafiklari'},
    ohm: {slug: 'ohms-law', title: 'Om qonuni'},
    resistance: {slug: 'resistance-in-a-wire', title: 'Sim qarshiligi'},
    battery: {slug: 'acid-base-solutions', title: 'Eritmalar laboratoriyasi'},
    circuitsAc: {slug: 'circuit-construction-kit-ac-virtual-lab', title: 'O‘zgaruvchan tok zanjiri'},
    buoyancy: {slug: 'buoyancy', title: 'Arximed kuchi'},
    gravityForce: {slug: 'gravity-force-lab-basics', title: 'Gravitatsiya kuchi laboratoriyasi'},
    colorVision: {slug: 'color-vision', title: 'Rangli ko‘rish'},
    neuron: {slug: 'neuron', title: 'Neyron signali'},
    ladybug: {slug: 'beers-law-lab', title: 'Yorug‘lik yutilishi laboratoriyasi'},
  });

  const rows = [
    ['l1','diffusion',1,'Ikki xil zarra qanday aralashishini va temperatura diffuziya tezligiga qanday ta’sir qilishini aniqlang.',['Ikki tomonga har xil zarrachalarni kiriting.','To‘siqni ochib, zarralarning aralashishini kuzating.','Temperaturani o‘zgartirib, tarqalish tezligini solishtiring.'],'Avval zarralarni idishning ikki tomoniga joylang, keyin o‘rtadagi to‘siqni oching.'],
    ['l2','atomic',1,'Atomlar orasidagi masofa o‘zgarganda tortishish va itarish kuchlari qanday almashishini aniqlang.',['Ikki atomni bir-biridan uzoq joylashtiring.','Atomlarni yaqinlashtirib kuch yo‘nalishini kuzating.','Muvozanat masofasini va atom o‘lchamini taqqoslang.'],'Atomlardan birini ushlab suring; kuch va potensial energiya grafigini birga kuzating.'],
    ['l3','molarity',1,'Modda miqdori, eritma hajmi va zarrachalar konsentratsiyasi orasidagi bog‘lanishni kuzating.',['Eritmaga modda qo‘shing.','Hajmni o‘zgartirmay konsentratsiyani kuzating.','Molyarlikni zarra soni bilan bog‘lab xulosa qiling.'],'Modda miqdorini bittadan oshirib, konsentratsiya ko‘rsatkichini kuzating.'],
    ['l4','concentration',1,'Eritmadagi zarrachalar miqdori va hajmni o‘zgartirib hisob natijasini tekshiring.',['Boshlang‘ich konsentratsiyani qayd eting.','Suv yoki erigan modda miqdorini o‘zgartiring.','Natijani c = n/V munosabati bilan tekshiring.'],'Bir paytda faqat suv yoki faqat erigan modda miqdorini o‘zgartiring.'],
    ['l5','gas',2,'Nasos, porshen va isitkich bilan ideal gaz holatini boshqaring.',['Nasos dastagini ushlab pastga tortib gaz qo‘shing.','Issiq–sovuq boshqaruvi bilan temperaturani o‘zgartiring.','Idish kengligini o‘zgartirib bosimni solishtiring.'],'Nasos tutqichini sichqoncha yoki barmoq bilan ushlab, oxirigacha pastga torting.'],
    ['l6','statesBasics',2,'Selsiy va Kelvin mazmunini zarrachalarning issiqlik harakati orqali tushuntiring.',['Termometr ko‘rsatishini boshlang‘ich holatda kuzating.','Isitkichni yoqib temperaturani oshiring.','Sovitib, zarrachalar harakati sekinlashishini ko‘ring.'],'Temperatura — zarrachalarning o‘rtacha kinetik energiyasi bilan bog‘liq.'],
    ['l7','gasesIntro',1,'Og‘ir va yengil gaz zarralarining tezliklarini bir xil temperaturada taqqoslang.',['Og‘ir zarralarni idishga kiriting.','Yengil zarralarni ham qo‘shing.','Ularning tezliklari va to‘qnashuvlarini solishtiring.'],'Ikki tur zarra uchun temperaturani bir xil saqlang.'],
    ['l8','gas',2,'Temperatura ortishi molekulalarning tezligiga qanday ta’sir qilishini o‘lchang.',['Gazni sovuq holatda kuzating.','Isitkich bilan temperaturani oshiring.','To‘qnashuvlar soni va bosimni taqqoslang.'],'Kenglik va zarra sonini o‘zgartirmay, faqat temperaturani o‘zgartiring.'],
    ['l9','gas',2,'Ideal gazning p, V, T va N kattaliklari orasidagi munosabatni kashf eting.',['Gaz miqdorini belgilab oling.','Hajmni o‘zgartirib p va T ni kuzating.','Natijani pV = NkT munosabati bilan bog‘lang.'],'Bir kattalikni o‘zgartirib, boshqa o‘lchagichlardagi javobni kuzating.'],
    ['l10','gas',2,'Temperatura o‘zgarmaganda bosim va hajm teskari proporsional ekanini tekshiring.',['Temperaturani o‘zgarmas saqlang.','Idish kengligini kamaytiring.','pV taxminan o‘zgarmas qolishini tekshiring.'],'Isitish va sovitishni ishlatmay, faqat idish devorini suring.'],
    ['l11','gas',2,'Bosim o‘zgarmaganda temperatura va hajm bog‘lanishini kuzating.',['Bosimni doimiy rejimga o‘tkazing.','Gazni asta qizdiring.','Hajmning temperatura bilan ortishini kuzating.'],'Doimiy bosim rejimi mavjud bo‘lsa, uni tanlab keyin isitishni boshlang.'],
    ['l12','gas',2,'Hajm o‘zgarmaganda temperatura oshishi bosimni oshirishini ko‘rsating.',['Idish kengligini mahkamlang.','Gazni qizdiring.','Bosim va temperatura nisbatini solishtiring.'],'Devorga tegmang; hajm o‘zgarmas holatda faqat issiq–sovuq boshqaruvini ishlating.'],
    ['l13','moleculeShapesBasics',1,'Atomlarni birlashtirib molekula fazoviy shakli va o‘lchami qanday hosil bo‘lishini kuzating.',['Markaziy atomga bog‘lar qo‘shing.','Elektron juftlari ta’sirida shakl o‘zgarishini kuzating.','Bog‘ burchaklarini solishtirib molekula o‘lchamini baholang.'],'Bog‘lar sonini bittadan o‘zgartiring va modelni aylantirib uch o‘lchamda ko‘ring.'],
    ['l14','gas',2,'Gaz qonunlari bo‘yicha masala shartlarini virtual tajribada tekshiring.',['Boshlang‘ich p, V va T ni qayd eting.','Bitta kattalikni topshiriqqa mos o‘zgartiring.','Yangi qiymatni formula bilan hisoblangan natijaga solishtiring.'],'O‘lchagichlarni o‘qishdan oldin sistema barqarorlashishini kuting.'],
    ['l15','energy',1,'Ichki energiya zarrachalarning harakati va o‘zaro ta’siriga bog‘liqligini ko‘ring.',['Bir jismni tanlab boshlang‘ich temperaturasini kuzating.','Unga energiya bering.','Energiya oqimi va temperatura o‘zgarishini bog‘lang.'],'Energiya belgilarining qayerdan kelib, qayerga ketayotganiga qarang.'],
    ['l16','friction',1,'Mexanik ish ishqalanish orqali ichki energiyaga aylanishini tajribada kuzating.',['Jismni sirt bo‘ylab harakatlantiring.','Ishqalanish koeffitsiyentini o‘zgartiring.','Bajarilgan ish va qizish orasidagi bog‘lanishni izohlang.'],'Jismni tezroq surib, sirt va jism temperaturasi qanday o‘zgarishini kuzating.'],
    ['l17','energy',1,'Issiqlik miqdori, massa va temperatura o‘zgarishi bog‘lanishini o‘rganing.',['Ikki xil materialni tanlang.','Ularga teng energiya bering.','Temperatura o‘zgarishini taqqoslang.'],'Bir xil isitish sharoitida materiallarning temperaturasi turlicha o‘zgaradi.'],
    ['l18','energy',1,'Q = cmΔT masalalarini vizual energiya almashinuvi bilan tekshiring.',['Jism va isitkichni tanlang.','Boshlang‘ich hamda oxirgi temperaturani qayd eting.','Natijani Q = cmΔT bilan bog‘lang.'],'Massa va materialni birma-bir o‘zgartirib taqqoslang.'],
    ['l19','energy',1,'Issiq va sovuq jismlar qanday qilib issiqlik muvozanatiga kelishini kuzating.',['Turli temperaturali ikkita jism tayyorlang.','Ularni issiqlik aloqasiga keltiring.','Temperaturalar tenglashishini kuzating.'],'Energiya issiq jismdan sovuq jismga o‘tadi.'],
    ['l20','energy',1,'Turli moddalarning solishtirma issiqlik sig‘imini tajribada taqqoslang.',['Teng massali ikki materialni tanlang.','Ularga bir xil energiya bering.','Qaysi material tezroq qizishini aniqlang.'],'Temperaturasi kamroq oshgan materialning issiqlik sig‘imi kattaroq bo‘ladi.'],
    ['l21','energy',2,'Yoqilg‘i energiyasi qanday qilib issiqlik va boshqa shakllarga aylanishini kuzating.',['Energiya manbaini ishga tushiring.','Energiya belgilarining yo‘lini kuzating.','Foydali va tarqalgan energiyani ajrating.'],'Energiya yo‘qolmaydi; u bir shakldan boshqasiga o‘tadi.'],
    ['l22','energy',2,'Termodinamikaning birinchi qonunini energiya balansi orqali tekshiring.',['Sistemaga issiqlik kiriting.','Ichki energiya va ishga ketgan ulushni kuzating.','Q = ΔU + A balansini izohlang.'],'Sistemaga kirgan energiyaning barcha chiqish yo‘llarini hisobga oling.'],
    ['l23','energy',2,'Birinchi qonun bo‘yicha masalaning energiya oqimini modelda ko‘rsating.',['Masala uchun energiya manbaini tanlang.','Foydali ishni hosil qiling.','Kirish va chiqish energiyalarini taqqoslang.'],'Diagrammadagi energiya belgilarini sanash balansni ko‘rishga yordam beradi.'],
    ['l24','skate',1,'Mexanik jarayonlarning qaytmasligini ishqalanish va issiqlik energiyasi orqali tushuntiring.',['Skeyterni yo‘lga qo‘yib energiya ustunlarini kuzating.','Ishqalanishni yoqing.','Mexanik energiyaning issiqlikka aylanishini izohlang.'],'Ishqalanish bo‘lsa, mexanik energiyaning bir qismi issiqlik ko‘rinishiga o‘tadi.'],
    ['l25','energy',1,'Turli temperaturali jismlarni aralashtirishdagi issiqlik balansini kuzating.',['Issiq va sovuq material tanlang.','Ularni issiqlik aloqasiga keltiring.','Yakuniy temperaturani oldindan taxmin qilib tekshiring.'],'Issiq jism bergan issiqlik sovuq jism olgan issiqlikka tenglashadi.'],
    ['l26','energy',2,'Ichki yonuv dvigatelidagi energiya aylanishlarini soddalashtirilgan tizimda kuzating.',['Kimyoviy energiya manbaini tanlang.','Mexanik harakat hosil qiling.','Issiqlik ko‘rinishida tarqalgan energiyani toping.'],'Dvigatel barcha energiyani foydali ishga aylantira olmaydi.'],
    ['l27','energy',2,'Issiqlik mashinasining energiya kirishi, foydali ishi va chiqindisini ajrating.',['Energiya manbaini yoqing.','Foydali harakatni kuzating.','Atrofga tarqalgan energiyani belgilang.'],'FIK foydali energiyaning kirish energiyasiga nisbatidir.'],
    ['l28','energy',2,'Issiqlik mashinasi FIKiga oid masalani energiya diagrammasida tekshiring.',['Kirish energiyasini kuzating.','Foydali energiya kanalini toping.','FIKni foizda baholab formulaga solishtiring.'],'Energiya belgilarining nisbatidan taxminiy FIKni toping.'],
    ['l29','greenhouse',1,'Issiqxona effekti yordamida issiqlik almashinuvini tahlil qiling.',['Quyosh nurlanishini kuzating.','Issiqxona gazlari miqdorini o‘zgartiring.','Yer temperaturasi va qaytgan energiyani taqqoslang.'],'Atmosferadagi gaz miqdorini bittadan o‘zgartirib uzoq muddatli temperaturani kuzating.'],
    ['l30','energy',2,'Qurilma samaradorligi va energiya yo‘qotishlarini amaliy tizimda tahlil qiling.',['Ikki xil energiya tizimini sinang.','Foydali chiqishni taqqoslang.','Qaysi tizim samaraliroq ekanini asoslang.'],'Kirish bir xil bo‘lsa, foydali chiqishi kattaroq tizim samaraliroq.'],
    ['l31','polarity',2,'Suyuqlik xossalarini molekulalararo tortishish bilan bog‘lang.',['Ikki atomli molekulani tanlang.','Bog‘ qutbliligini o‘zgartiring.','Molekulalar tortishishidagi farqni kuzating.'],'Qutblilik ortishi molekulalararo ta’sirni kuchaytirishi mumkin.'],
    ['l32','polarity',2,'Ho‘llash va kapillyarlikni molekula qutbliligi nuqtayi nazaridan tushuntiring.',['Bog‘ dipolini kuzating.','Molekula yo‘nalishini elektr maydonda sinang.','Natijani ho‘llash hodisasi bilan bog‘lang.'],'Suyuqlik va sirt orasidagi tortishish ichki tortishishdan kuchli bo‘lsa, ho‘llash yuz beradi.'],
    ['l33','pressure',1,'Suyuqlik chuqurligi ortishi bilan gidrostatik bosim qanday o‘zgarishini o‘lchang.',['Datchikni suyuqlikka tushiring.','Chuqurlikni o‘zgartirib bosimni o‘lchang.','Zichlikni o‘zgartirib natijani taqqoslang.'],'Zichlik va chuqurlik ortishi bilan suyuqlik bosimi ortadi.'],
    ['l34','polarity',2,'Sirt taranglikni molekulalararo kuchlar modeli bilan izohlang.',['Molekula qutbliligini o‘zgartiring.','Molekulalar yo‘nalishini kuzating.','Kuchli tortishishni sirt tarangligi bilan bog‘lang.'],'Sirt molekulalariga ta’sir etuvchi natijaviy kuch suyuqlik ichkarisiga yo‘naladi.'],
    ['l35','states',1,'Atomlarning fazoviy joylashuvi modda tuzilishini qanday belgilashini molekula modeli orqali o‘rganing.',['Markaziy atom va bog‘larni joylashtiring.','Bog‘ burchaklarini uch o‘lchamda kuzating.','Tartibli tuzilmani kristall panjara bilan bog‘lang.'],'Modelni aylantirib, atomlarning fazodagi simmetriyasiga e’tibor bering.'],
    ['l36','hookes',1,'Qattiq jism deformatsiyasi va elastiklik kuchini prujina bilan o‘rganing.',['Prujinaga kuch qo‘llang.','Uzayishni chizg‘ich bilan o‘lchang.','Kuchni o‘zgartirib F va Δl ni taqqoslang.'],'Kuchni oshirib uzayishni kuzating va Huk qonunini tekshiring.'],
    ['l37','springs',1,'Guk qonuniga oid masalalarni virtual prujinada tekshiring.',['Prujina qattiqligini tanlang.','Ma’lum massani osib uzayishni o‘lchang.','F = kΔl bilan natijani tekshiring.'],'Og‘irlik kuchini F = mg orqali topib, prujina kuchiga tenglashtiring.'],
    ['l38','states',2,'Erish va qotishni zarrachalar harakati hamda faza diagrammasi bilan kuzating.',['Qattiq moddani tanlang.','Isitib erish chegarasidan o‘tkazing.','Sovitib qayta qotishini kuzating.'],'Isitish paytida temperatura bir muddat o‘zgarmay, energiya fazani o‘zgartirishi mumkin.'],
    ['l39','states',2,'Yashirin issiqlikning faza almashinuvidagi rolini tushuntiring.',['Faza almashinuvi boshlanishini toping.','Isitishni davom ettirib temperaturani kuzating.','Energiya nima uchun temperaturani darhol oshirmasligini ayting.'],'Faza o‘zgarishida energiya molekulalararo bog‘larni o‘zgartirishga sarflanadi.'],
    ['l40','states',2,'Bug‘lanish va kondensatsiyani zarrachalar modeli orqali kuzating.',['Suyuqlikni asta qizdiring.','Gaz holatiga o‘tgan zarralarni kuzating.','Sovitib kondensatsiyani hosil qiling.'],'Gaz holatidagi zarralar bir-biridan uzoq va tez harakat qiladi.'],
    ['l41','pressure',1,'Atmosfera va suyuqlik bosimini turli balandlik hamda chuqurliklarda solishtiring.',['Datchikni havoda kuzating.','Uni suyuqlikka tushiring.','Chuqurlik ortganda bosim qanday o‘zgarishini yozing.'],'Bosim o‘lchagichni barmoq yoki sichqoncha bilan erkin suring.'],
    ['l42','states',2,'Nisbiy namlikni bug‘lanish va kondensatsiya muvozanati bilan bog‘lang.',['Suyuqlikni qizdirib bug‘ hosil qiling.','Sovutib kondensatsiyani kuzating.','Temperatura namlikka qanday ta’sir qilishini izohlang.'],'Issiq havo ko‘proq suv bug‘ini sig‘dira oladi.'],
    ['l43','states',2,'Faza va namlikka oid masalalarni zarracha modelida tekshiring.',['Boshlang‘ich holatni tanlang.','Temperaturani masala shartiga mos o‘zgartiring.','Kuzatuvni faza diagrammasi bilan bog‘lang.'],'Avval temperatura yo‘nalishini, keyin faza o‘zgarishini aniqlang.'],
    ['l44','moleculesLight',1,'Yorug‘likning turli molekulalar bilan o‘zaro ta’sirini va elektromagnit to‘lqinlarni kuzating.',['Yorug‘lik turini tanlang.','Turli molekulalarni nurlantiring.','Yutilish yoki o‘tish holatlarini taqqoslang.'],'Har bir molekula faqat ma’lum chastotadagi nurni kuchli yutadi.'],
    ['l45','light',1,'Yorug‘likning qaytish va sinish qonunlarini lazer nuri bilan kashf eting.',['Lazerni yoqing.','Tushish burchagini o‘zgartiring.','Qaytish va sinish burchaklarini transportir bilan o‘lchang.'],'Lazer tutqichini sudrab burchakni o‘zgartiring.'],
    ['l46','light',1,'Qaytish va sinish masalalaridagi burchaklarni simulyatsiyada tekshiring.',['Birinchi muhitni tanlang.','Tushish burchagini masala shartiga moslang.','O‘lchangan sinish burchagini hisob bilan solishtiring.'],'Normal chizig‘i burchaklarni to‘g‘ri o‘lchash uchun asos bo‘ladi.'],
    ['l47','light',1,'To‘la ichki qaytishni tajribada hosil qilib, kritik burchakni toping.',['Yorug‘likni zich muhitdan siyrak muhitga yo‘naltiring.','Tushish burchagini asta oshiring.','Singan nur yo‘qoladigan kritik burchakni toping.'],'Pastki muhitning sindirish ko‘rsatkichini yuqoridagidan kattaroq tanlang.'],
    ['l48','light',1,'To‘la ichki qaytish masalalarini kritik burchak orqali tekshiring.',['Muhitlarning sindirish ko‘rsatkichlarini tanlang.','Kritik burchakni tajribada toping.','Natijani sin αkr = n₂/n₁ bilan tekshiring.'],'Tushish burchagini kritik qiymat atrofida juda sekin o‘zgartiring.'],
    ['l49','light',1,'Shishaning sindirish ko‘rsatkichini burchaklarni o‘lchab aniqlang.',['Havo va shisha muhitini tanlang.','Tushish hamda sinish burchaklarini o‘lchang.','n = sinα/sinγ bo‘yicha hisoblang.'],'Transportir va normal chizig‘ini yoqing.'],
    ['l50','opticsBasics',1,'Yig‘uvchi va sochuvchi linzalarda nurlar yo‘lini kuzating.',['Linza turini tanlang.','Parallel nurlarni linzadan o‘tkazing.','Fokus nuqtasini toping.'],'Linza egriligi yoki fokus masofasini o‘zgartirib ko‘ring.'],
    ['l51','optics',1,'Yupqa linzada jism tasviri qayerda va qanday hosil bo‘lishini o‘rganing.',['Jismni linza oldiga joylashtiring.','Jismni fokusga yaqin va uzoq suring.','Tasvirning kattaligi hamda yo‘nalishini taqqoslang.'],'Jismni optik o‘q bo‘ylab sudrang; asosiy nurlar kesishgan joy tasvirdir.'],
    ['l52','optics',1,'Linza formulasiga oid masalalarni real vaqt nurlari bilan tekshiring.',['Fokus masofasini belgilang.','Jism masofasini masala shartiga moslang.','Tasvir masofasini o‘lchab formulaga solishtiring.'],'1/F = 1/d + 1/f munosabatida barcha masofalarni bir xil birlikda oling.'],
    ['l53','optics',1,'Linzaning optik kuchi fokus masofasidan tajribada aniqlang.',['Parallel nurlarni linzaga yo‘naltiring.','Fokus masofasini chizg‘ich bilan o‘lchang.','D = 1/F bo‘yicha optik kuchni toping.'],'Fokus masofasini metrda olsangiz, natija dioptriyada chiqadi.'],
    ['l54','optics',1,'Optik asboblarda linzalar qanday tasvir hosil qilishini o‘rganing.',['Jism va linzani joylashtiring.','Ekranni tiniq tasvir hosil bo‘lguncha suring.','Kattalashtirishni jism va tasvir balandligi bilan taqqoslang.'],'Ekran faqat haqiqiy tasvirni tutadi.'],
    ['l55','optics',1,'Ko‘zning fokuslashini linza va ekran modeli orqali tushuntiring.',['Jismni turli masofalarga qo‘ying.','Tasvir tekisligini kuzating.','Fokus masofasini o‘zgartirib tiniq tasvir hosil qiling.'],'Ko‘z gavhari egriligini o‘zgartirib, tasvirni to‘r pardaga fokuslaydi.'],
    ['l56','optics',1,'Ko‘z va optik asboblarga oid masalalarni nurlar diagrammasida tekshiring.',['Masala bo‘yicha jism masofasini sozlang.','Mos fokus masofasini tanlang.','Tasvir xususiyatlarini formula bilan solishtiring.'],'Avval nurlar diagrammasidan tasvir haqiqiy yoki mavhumligini aniqlang.'],
    ['l57','spectrum',1,'Quyosh nurlanishi temperaturaga qanday bog‘liqligini spektr orqali o‘rganing.',['Temperaturani Quyosh qiymatiga yaqinlashtiring.','Spektr cho‘qqisining o‘rnini kuzating.','Temperatura va rang orasidagi bog‘lanishni ayting.'],'Temperatura oshganda spektr cho‘qqisi qisqaroq to‘lqinlarga siljiydi.'],
    ['l58','gravity',1,'Yagona fizik manzarada gravitatsiya, harakat va energiya bog‘lanishini orbitalarda ko‘ring.',['Ikki osmon jismini tanlang.','Massa va tezlikni o‘zgartiring.','Barqaror orbitaga erishib sababini tushuntiring.'],'Tezlik juda kichik bo‘lsa jism qulaydi, juda katta bo‘lsa orbitadan chiqadi.'],
    ['l59','circuits',1,'Zamonaviy texnologik qurilmani elektr zanjiri sifatida yig‘ib, energiya uzatilishini tahlil qiling.',['Batareya, sim va iste’molchini ulang.','Kalit bilan zanjirni ishga tushiring.','Tok va kuchlanishni o‘lchab qurilmani yaxshilang.'],'Avval sodda yopiq zanjir quring, keyin o‘lchov asboblari va qo‘shimcha element qo‘shing.'],
  ];

  const official = (simulation, screen = 1) => ({kind: 'official', simulation, screen});
  // Har bir darsga uning fizik mazmuniga eng yaqin rasmiy simulyatsiya ulanadi.
  // Bir mavzu oilasidagi darslarda bir xil laboratoriyaning turli ekrani qayta
  // ishlatilishi mumkin: mavzuga moslik sun’iy "takrorlanmaslik"dan muhimroq.
  const assignmentOverrides = Object.freeze({
    l1: official('diffusion', 1),
    l2: official('quantumInterference', 1),
    l3: official('molarity', 1),
    l4: official('concentration', 1),
    l5: official('gas', 2),
    l6: official('gasesIntro', 1),
    l7: official('atomic', 1),
    l8: official('moleculeShapesBasics', 1),
    l9: official('moleculeShapes', 1),
    l10: official('ramp', 1),
    l11: official('electricHockey', 1),
    l12: official('vectors', 1),
    l13: official('photoelectric', 1),
    l14: official('rutherford', 1),
    l15: official('energy', 1),
    l16: official('friction', 1),
    l17: official('skateBasics', 1),
    l18: official('skate', 1),
    l19: official('collision', 1),
    l20: official('springBasics', 1),
    l21: official('circuitsAc', 1),
    l22: official('pendulum', 1),
    l23: official('forces', 1),
    l24: official('projectile', 1),
    l25: official('balance', 1),
    l26: official('generator', 1),
    l27: official('faraday', 1),
    l28: official('projectileData', 1),
    l29: official('greenhouse', 1),
    l30: official('gravityForce', 1),
    l31: official('polarity', 2),
    l32: official('battery', 1),
    l33: official('pressure', 1),
    l34: official('ladybug', 1),
    l35: official('hydrogen', 1),
    l36: official('hookes', 1),
    l37: official('springs', 1),
    l38: official('states', 2),
    l39: official('buoyancy', 1),
    l40: official('density', 1),
    l41: official('solarSystem', 1),
    l42: official('capacitor', 1),
    l43: official('normalModes', 1),
    l44: official('wavesIntro', 1),
    l45: official('light', 1),
    l46: official('interference', 1),
    l47: official('quantumTunneling', 1),
    l48: official('fourier', 1),
    l49: official('moleculesLight', 1),
    l50: official('opticsBasics', 1),
    l51: official('optics', 1),
    l52: official('colorVision', 1),
    l53: official('chargesFields', 1),
    l54: official('sound', 1),
    l55: official('neuron', 1),
    l56: official('travoltage', 1),
    l57: official('spectrum', 1),
    l58: official('gravity', 1),
    l59: official('circuits', 1),
  });
  const assignments = Object.freeze(Object.fromEntries(rows.map(([id, simulation, screen]) => [id, assignmentOverrides[id] || official(simulation, screen)])));

  const lessons = Object.fromEntries(rows.map(([id, ignoredSimulation, ignoredScreen, mission, checklist, hint]) => {
    const assignment = assignments[id];
    return [id, Object.freeze({id, ...assignment, mission, checklist: Object.freeze(checklist), hint})];
  }));

  const buildUrl = config => {
    const simulation = simulations[config.simulation];
    if (!simulation) return '';
    const locale = simulation.locale || 'uz';
    const base = `https://phet.colorado.edu/sims/html/${simulation.slug}/latest/${simulation.slug}_${locale}.html`;
    return config.screen ? `${base}?screens=${config.screen}` : base;
  };

  const buildThumbnail = config => {
    if (!config) return '';
    const simulation = simulations[config.simulation];
    return simulation ? `https://phet.colorado.edu/sims/html/${simulation.slug}/latest/${simulation.slug}-600.png` : '';
  };

  window.IDROK_PHET = Object.freeze({
    version: '2026.07-official-library',
    simulations,
    lessons: Object.freeze(lessons),
    catalog: Object.freeze(Object.entries(simulations).map(([key, simulation]) => Object.freeze({key, ...simulation}))),
    buildUrl,
    buildThumbnail,
  });
})();
